name: Feature Pull Request

on:
  pull_request:

jobs:
  prepare:
    name: Prepare Origin Branch for merge
    runs-on: ubuntu-latest
    steps:
      - uses: havmedia/hav_odoo_maintainer_tools/prepare-general@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}